accelerator: gpu
accumulate_grad_batches: 16
alpha: 0.99
amsgrad: false
batch_size: 16
betas:
- 0.9
- 0.999
centered: false
cf_classify_edits: false
ckpt: experiments/masker_my_movies_longt5/versionybf3lkhs/checkpoints/epoch=4.ckpt
dampening: 0.0
default_root_dir: experiments/masker_my_movies_longt5
devices: 1
dm: my_movies
dropout: 0.1
explainer: sparsemap
explainer_pre_mlp: true
explainer_requires_grad: true
gen_arch: google/long-t5-tglobal-base
gen_emb_requires_grad: false
gen_encoder_requires_grad: false
gen_use_decoder: false
gpu_log: false
gradient_clip_val: 5.0
ignore_neutrals: false
is_original: true
lambd: 0.0001
load_label_encoder: false
load_tokenizer: false
lr: 5.0e-05
max_dataset_size: null
max_epochs: 15
max_seq_len: 512
min_epochs: 3
model: transformer_spectra
momentum: 0.0
monitor: val_ff_accuracy
monitor_mode: max
monitor_patience: 10
nesterov: false
no_fit: false
no_test: true
num_workers: 1
optimizer: adamw
precision: 32
pred_arch: google/long-t5-tglobal-base
pred_bidirectional: false
pred_emb_requires_grad: false
pred_encoder_requires_grad: true
pred_output_requires_grad: true
save_counterfactuals: false
save_edits: false
save_label_encoder: false
save_rationales: false
save_tokenizer: false
seed: 0
selection_faithfulness: true
selection_mask: false
selection_vector: zero
shared_gen_pred: false
sparsemap_budget: 30
sparsemap_temperature: 0.01
sparsemap_transition: 0.01
t0: 1000000.0
tokenizer: google/long-t5-tglobal-base
vocab_min_occurrences: 1
wandb_entity: gian-kalyva-national-technical-university-of-athens
wandb_project: movies_longt5_masker
weight_decay: 1.0e-06
